export const ALL_TODOS_REQUEST = "ALL_TODOS_REQUEST";
export const ALL_TODOS_SUCCESS = "ALL_TODOS_SUCCESS";

export const CREATE_TODO = "CREATE_TODO_SUCCESS";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";

export const SINGLE_TODO_REQUEST = "SINGLE_TODO_REQUEST";
export const SINGLE_TODO_SUCCESS = "SINGLE_TODO_SUCCESS";
